### ISSUE TITLE
remove "quiet" to enable debug output.

### ISSUE THREAD

**Issue by mrdunk** [ynkjm/ubuntu-serial-install#1]
hi,
thanks for putting this up.
it saved me a bit of time installing on a headless system.

something i found useful was to remove the "-- quiet" key word which allows the boot massages to be displayed on screen.

also for some reason i needed to remove the "--" symbols before the "console=serial,115220n8" part.

**Comment by ynkjm** [comment]
Hi @mrdunk 

Thank you for your suggestion.
I modified the boot parameter in the latest version.

Could you try?

**Comment by nightseas** [comment]
I've tried your latest version with Ubuntu Server 16.04.2 LTS on my blade server and it worked.
These configurations were already there after installation:
/etc/default/grup
```
GRUB_TERMINAL=serial
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1"
```

**Comment by ynkjm** [comment]
Thanks, @nightseas
